kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: docker-build-init
  labels:
    name: docker-build-init
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'ignition-init:0.0.5'
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  source:
    type: Git
    git:
      uri: 'https://github.com/KevinLapagna/ignition-openshift.git'
    contextDir: ignition-init