apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    ignition.service: gateway
  name: gateway
spec:
  ports:
  - name: "9088"
    port: 9088
    targetPort: 8088
  - name: "9043"
    port: 9043
    targetPort: 8043
  selector:
    ignition.service: gateway
status:
  loadBalancer: {}
