apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    ignition.service: gateway
  name: gateway
spec:
  ports:
  - name: "http"
    port: 8088
    targetPort: 8088
  selector:
    ignition.service: gateway
status:
  loadBalancer: {}
